export enum NotificationType {
  // Land Parcel Events
  PARCEL_TRANSFER_SENT = 'PARCEL_TRANSFER_SENT',
  PARCEL_TRANSFER_RECEIVED = 'PARCEL_TRANSFER_RECEIVED',
  PARCEL_MINTED = 'PARCEL_MINTED',
  HEIR_DESIGNATED = 'HEIR_DESIGNATED',

  // Inheritance Events
  INHERITANCE_REQUESTED = 'INHERITANCE_REQUESTED',
  INHERITANCE_VERIFIED = 'INHERITANCE_VERIFIED',
  INHERITANCE_COMPLETED = 'INHERITANCE_COMPLETED',
  INHERITANCE_REJECTED = 'INHERITANCE_REJECTED',

  // Expropriation Events
  EXPROPRIATION_FLAGGED = 'EXPROPRIATION_FLAGGED',
  COMPENSATION_DEPOSITED = 'COMPENSATION_DEPOSITED',
  COMPENSATION_CLAIMED = 'COMPENSATION_CLAIMED',
  EXPROPRIATION_COMPLETED = 'EXPROPRIATION_COMPLETED',
  EXPROPRIATION_CANCELLED = 'EXPROPRIATION_CANCELLED',

  // Compliance Events
  COMPLIANCE_VIOLATION = 'COMPLIANCE_VIOLATION',
  COMPLIANCE_ASSESSMENT_COMPLETED = 'COMPLIANCE_ASSESSMENT_COMPLETED',
  FINE_ISSUED = 'FINE_ISSUED',
  INCENTIVE_AWARDED = 'INCENTIVE_AWARDED',
  COMPLIANCE_DEADLINE_REMINDER = 'COMPLIANCE_DEADLINE_REMINDER',

  // Dispute Events
  DISPUTE_CREATED = 'DISPUTE_CREATED',
  DISPUTE_RECEIVED = 'DISPUTE_RECEIVED',
  DISPUTE_EVIDENCE_SUBMITTED = 'DISPUTE_EVIDENCE_SUBMITTED',
  DISPUTE_ESCALATED = 'DISPUTE_ESCALATED',
  DISPUTE_RULING = 'DISPUTE_RULING',
  DISPUTE_RESOLVED = 'DISPUTE_RESOLVED',
  DISPUTE_APPEALED = 'DISPUTE_APPEALED',

  // Governance Events
  PROPOSAL_CREATED = 'PROPOSAL_CREATED',
  PROPOSAL_VOTING_STARTED = 'PROPOSAL_VOTING_STARTED',
  PROPOSAL_VOTING_ENDING = 'PROPOSAL_VOTING_ENDING',
  PROPOSAL_EXECUTED = 'PROPOSAL_EXECUTED',
  PROPOSAL_DEFEATED = 'PROPOSAL_DEFEATED',
  VOTE_CAST = 'VOTE_CAST',

  // System Events
  SYSTEM_MAINTENANCE = 'SYSTEM_MAINTENANCE',
  SYSTEM_UPDATE = 'SYSTEM_UPDATE',
  SECURITY_ALERT = 'SECURITY_ALERT',
  ACCOUNT_VERIFICATION = 'ACCOUNT_VERIFICATION',
  PASSWORD_RESET = 'PASSWORD_RESET',

  // Transaction Events
  TRANSACTION_CONFIRMED = 'TRANSACTION_CONFIRMED',
  TRANSACTION_FAILED = 'TRANSACTION_FAILED',
  TRANSACTION_PENDING = 'TRANSACTION_PENDING',

  // General
  WELCOME = 'WELCOME',
  REMINDER = 'REMINDER',
  ANNOUNCEMENT = 'ANNOUNCEMENT',
  NEWSLETTER = 'NEWSLETTER',
  CUSTOM = 'CUSTOM',
}

export enum NotificationStatus {
  PENDING = 'PENDING',
  SENT = 'SENT',
  DELIVERED = 'DELIVERED',
  READ = 'READ',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPIRED',
}

export enum NotificationChannel {
  WEB = 'WEB',
  EMAIL = 'EMAIL',
  PUSH = 'PUSH',
  SMS = 'SMS',
  WEBHOOK = 'WEBHOOK',
}

export enum NotificationPriority {
  LOW = 1,
  NORMAL = 2,
  HIGH = 3,
  URGENT = 4,
  CRITICAL = 5,
}

export enum NotificationFrequency {
  IMMEDIATE = 'IMMEDIATE',
  HOURLY = 'HOURLY',
  DAILY = 'DAILY',
  WEEKLY = 'WEEKLY',
  MONTHLY = 'MONTHLY',
  NEVER = 'NEVER',
}

