export enum UserRole {
  ADMIN = 'ADMIN',
  USER = 'USER',
  MODERATOR = 'MODERATOR',
  LAND_REGISTRAR = 'LAND_REGISTRAR',
  NOTARY = 'NOTARY',
  ANALYST = 'ANALYST',
  GOVERNMENT_OFFICIAL = 'GOVERNMENT_OFFICIAL',
  DEVELOPER = 'DEVELOPER',
  AUDITOR = 'AUDITOR',
  GUEST = 'GUEST',
  RLMUA_OFFICIAL = "RLMUA_OFFICIAL",
}
